### ISSUE TITLE
Move aw-transform to aw-analysis?

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-research#5]
Why are aw-transform and aw-analysis different packages?

Since i am splitting all transforms from the aw-core package to a aw-transforms package in aw-core on dev/transform-next, wouldn't it make more sense to move it here?

It would be nice if we could merge them so we can have all transforms in one place.

It seems like there are two types of files in this repo currently, transforms and visualization/plotting.
If we would merge these, we could split it into three packages in this repo: aw-transform, aw-visualize and aw-query.

Whether you then want to retrieve the data client-side or server-side would simply be an option.

Also, since aw-core has such essential features it would be nice if we did less changes there to keep it more stable. The aw-transform stuff will likely be more rapidly developed since there's such an incredible amount of things you could possibly want to analyze.

If someone then wanted to do their own analysis with python, they could fetch all events with aw-client and then use any transform they'd like.

**Comment by ErikBjare** [comment]
I've been thinking about this too. I have a few problems though:

 - I want to keep the number of submodules down
 - The transforms that are used in query2 need to be stable, aw-analysis is a highly unstable repo right now.

>Since i am splitting all transforms from the aw-core package to a aw-transforms package in aw-core on dev/transform-next, wouldn't it make more sense to move it here?

Yeah, but point 1 above is kind of an issue.

>It seems like there are two types of files in this repo currently, transforms and visualization/plotting. If we would merge these, we could split it into three packages in this repo: aw-transform, aw-visualize and aw-query.

I'm against splitting it up much further. One repo `aw-analysis` for transforms, visualization, and querying would be ok.

>Also, since aw-core has such essential features it would be nice if we did fewer changes there to keep it more stable. The aw-transform stuff will likely be more rapidly developed since there's such an incredible amount of things you could possibly want to analyze.

Agreed, that would be the main thing in favor of moving stuff out of aw-core. Would you be in favor of moving query2 to aw-analysis as well? Regardless, I think we should merge dev/transform-next into aw-core first and then move stuff over once we've decided on a package structure.

Proposal for a package structure:

```
aw_analysis
├── query
├── transform
└── visualization
```

Here's the dependency graph that would give:

![outfile](https://user-images.githubusercontent.com/1405370/32225052-102118ac-be44-11e7-93dc-fa872cc8c911.png)

You can build the dependency graph yourself since https://github.com/ActivityWatch/activitywatch/commit/8e2040b53330433ea41e29688c14f698633716a2

**Comment by ErikBjare** [comment]
Since we moved the transforms to `aw_transform` in `aw-core` and this package became stale I renamed it to `aw-research` and removed transforms that are now in `aw_transform`. The intended purpose of this repo is now to just be a playground for analysis and visualization.

Closing this issue since that basically resolves things.
